kind: ConfigMap
apiVersion: v1
metadata:
  name: sitest
data:
  sitest.yaml: |
    default:
      interval: 1m
    sites:
      "https://golang.org":
         interval: 15s
      "https://api.myip.com/": {}
      "http://example.com/": {}
